plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'old_runner/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25
